version: '3.8'
services: 
    main:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0 --port=8001'
        volumes:
            - .:/app
        ports:
            - 8001:8001
        depends_on: 
            - db

    queue:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan queue:work'
        depends_on: 
            - db        

    db:
        platform: linux/x86_64
        image: mysql:8.0
        environment: 
            MYSQL_DATABASE: laravel
            MYSQL_ROOT: root
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3306:3306